export const flowers = [{
    id: 1,
    name: "Holly",
    price: 30,
    description: "You know that moment when the morning sun starts to seep through the window? When the day is young, fresh, still. Holly captures all those feelings with her seasonal yellow tulips & vibrant alstroemeria.",
    inside: "16 stems including tulips, solidago, eucalyptus and alstroemeria.",
    img: "https://images.unsplash.com/photo-1567696153798-9111f9cd3d0d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Hand-tied flowers",
    bestseller: true,
    quantity: 0,
},
{
    name: "Nova",
    id: 2,
    price: 38,
    description: "Flower arranging is so soul soothing. And these pure-white blooms make it extra zen.",
    inside: "17 stems including white roses (that symbolise affection), snapdragons, asters and greenbells.",
    img: "https://images.unsplash.com/photo-1567418938902-aa650a3eb346?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=794&q=80",
    type: "Hand-tied flowers",
    bestseller: false,
    quantity: 0,
}, {
    name: "Daisy",
    id: 3,
    price: 40,
    description: "A quintessential Liberty floral that whisks you away to a dreamy cottage garden, it pairs perfectly with Daisy`s soft pink and honey-gold roses. ",
    inside: "18 stems including snapdragons, statice, roses, pistache, chrysanthemums and sweet williams.",
    img: "https://images.unsplash.com/photo-1557925923-6885735abfb1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80",
    type: "Luxury flowers",
    bestseller: true,
    quantity: 0,
}, {
    name: "Marry",
    id: 4,
    price: 32,
    description: "There are few things more relaxing than sitting outside in nature. With wildflowers all around you. And delicate grass stems gently brushing your skin.",
    inside: "47 Dried stems including spray roses, poppy seed heads, lavender and dried linum.",
    img: "https://images.unsplash.com/photo-1622658641561-fe2ca339b039?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Dried flowers",
    bestseller: false,
    quantity: 0,
}, {
    name: "Millie",
    id: 5,
    price: 40,
    description: "You know that flicker of excitement you get when you notice the days finally getting longer? Unwrapping our Millie feels just like that. ",
    inside: "24 stems including sunflowers, carnations, asters, craspedia, roses, limonium and solidago.",
    img: "https://images.unsplash.com/photo-1603178455924-ef33372953bb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80",
    type: "Luxury flowers",
    bestseller: true,
    quantity: 0,
}, {
    name: "Phoebe",
    id: 6,
    price: 45,
    description: "A retro-pop medley of wild, vibrant hues, a dazzle of hot coral roses, indigo limonium, and daisy-like asters, she’s the life and soul of the party.",
    inside: "20 stems including roses, hypericum berries, asters, alstroemeria, limonium and dianthus.",
    img: "https://images.unsplash.com/photo-1533616688419-b7a585564566?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Luxury flowers",
    bestseller: false,
    quantity: 0,
}, {
    name: "Yui",
    id: 7,
    price: 37,
    description: "Know someone who could use a relaxing do-nothing-day at home? Our Yui is here to help you treat them to one.",
    inside: "21 stems including stocks, carnations, pistache and limonium.",
    img: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Hand-tied flowers",
    bestseller: false,
    quantity: 0,
}, {
    name: "Minnie",
    id: 8,
    price: 30,
    description: "If we could pack all the shades of an early summer sunrise into a box, it’d look a lot like this. Soft, yet vibrant yellows, peaches and lilacs, Minnie is here to wow.",
    inside: "44 Dried stems including helichrysum, statice, poppy seed heads, amaranthus, spray roses and lavender.",
    img: "https://plus.unsplash.com/premium_photo-1676383427728-5e6df7edcf02?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=826&q=80",
    type: "Dried flowers",
    bestseller: false,
    quantity: 0,
},
{
    name: "Bliss",
    id: 9,
    price: 42,
    description: "Know someone who’s missing out on a spring getaway this year? We can’t promise you all-day sunshine, but this bouquet is sure to bring a breath of fresh air.",
    inside: "18 stems including softly scented freesias, sweet williams, tulips and meadowy foliage.",
    img: "https://images.unsplash.com/photo-1610841802859-94794ea50e1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80",
    type: "Hand-tied flowers",
    bestseller: false,
    quantity: 0,
},
{
    name: "Sunny",
    id: 10,
    price: 30,
    description: "Waxflower’s known for its sweet, relaxing scent. And our Seiko has got it in spades. So if you've had a busy week/month/year, this bouquet could be just the thing for taking a ‘you’ moment.",
    inside: "15 stems including stocks, carnations, sweet williams, limonium, chrysanthemums and waxflower.",
    img: "https://images.unsplash.com/photo-1591886960528-5dcaeec039b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80",
    type: "Luxury flowers",
    bestseller: false,
    quantity: 0,
},
{
    name: "Flora",
    id: 11,
    price: 25,
    description: "Waxflower’s known for its sweet, relaxing scent. And our Seiko has got it in spades. So if you've had a busy week/month/year, this bouquet could be just the thing for taking a ‘you’ moment.",
    inside: "15 stems including stocks, carnations, sweet williams, limonium, chrysanthemums and waxflower.",
    img: "https://images.unsplash.com/photo-1619854815830-de79cc821fce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Dried flowers",
    bestseller: false,
    quantity: 0,
},
{
    name: "Joe",
    id: 12,
    price: 28,
    description: "They’re the yin to your yang. Bonnie to your Clyde. And this wild bunch is as enduring as your No.1.",
    inside: "Dried stems including achillea, craspedia, limonium, carthamus, lagurus, helichrysum, spray roses, dried oats, linum and phalaris.",
    img: "https://images.unsplash.com/photo-1607087007621-ef43a693ed80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Dried flowers",
    bestseller: false,
    quantity: 0,
},

{
    name: "Lorry",
    id: 13,
    price: 31,
    description: "They’re the yin to your yang. Bonnie to your Clyde. And this wild bunch is as enduring as your No.1.",
    inside: "Dried stems including achillea, craspedia, limonium, carthamus, lagurus, helichrysum, spray roses, dried oats, linum and phalaris.",
    img: "https://images.unsplash.com/photo-1587317996237-eddd7e834d84?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Hand-tied flowers",
    bestseller: false,
    quantity: 0,
},



];