export const flowers = [{
    name: "Holly",
    price: 30,
    description: "You know that moment when the morning sun starts to seep through the window? When the day is young, fresh, still. Holly captures all those feelings with her seasonal yellow tulips & vibrant alstroemeria.",
    inside: "16 stems including tulips, solidago, eucalyptus and alstroemeria.",
    img: "https://images.unsplash.com/photo-1567696153798-9111f9cd3d0d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Hand-tied flowers",
},
{
    name: "Nova",
    price: 38,
    description: "Flower arranging is so soul soothing. And these pure-white blooms make it extra zen.",
    inside: "17 stems including white roses (that symbolise affection), snapdragons, asters and greenbells.",
    img: "https://images.unsplash.com/photo-1567418938902-aa650a3eb346?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=794&q=80",
    type: "Hand-tied flowers",
}, {
    name: "Daisy",
    price: 40,
    description: "A quintessential Liberty floral that whisks you away to a dreamy cottage garden, it pairs perfectly with Daisy`s soft pink and honey-gold roses. ",
    inside: "18 stems including snapdragons, statice, roses, pistache, chrysanthemums and sweet williams.",
    img: "https://images.unsplash.com/photo-1557925923-6885735abfb1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80",
    type: "Luxury flowers",
}, {
    name: "Marry",
    price: 32,
    description: "There are few things more relaxing than sitting outside in nature. With wildflowers all around you. And delicate grass stems gently brushing your skin.",
    inside: "47 Dried stems including spray roses, poppy seed heads, lavender and dried linum.",
    img: "https://images.unsplash.com/photo-1622658641561-fe2ca339b039?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Dried flowers",
}, {
    name: "Millie",
    price: 40,
    description: "You know that flicker of excitement you get when you notice the days finally getting longer? Unwrapping our Millie feels just like that. ",
    inside: "24 stems including sunflowers, carnations, asters, craspedia, roses, limonium and solidago.",
    img: "https://images.unsplash.com/photo-1603178455924-ef33372953bb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80",
    type: "Luxury flowers",
}, {
    name: "Phoebe",
    price: 45,
    description: "A retro-pop medley of wild, vibrant hues, a dazzle of hot coral roses, indigo limonium, and daisy-like asters, she’s the life and soul of the party.",
    inside: "20 stems including roses, hypericum berries, asters, alstroemeria, limonium and dianthus.",
    img: "https://images.unsplash.com/photo-1533616688419-b7a585564566?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Luxury flowers",
}, {
    name: "Yui",
    price: 37,
    description: "Know someone who could use a relaxing do-nothing-day at home? Our Yui is here to help you treat them to one.",
    inside: "21 stems including stocks, carnations, pistache and limonium.",
    img: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    type: "Hand-tied flowers",
}, {
    name: "Minnie",
    price: 30,
    description: "If we could pack all the shades of an early summer sunrise into a box, it’d look a lot like this. Soft, yet vibrant yellows, peaches and lilacs, Minnie is here to wow.",
    inside: "44 Dried stems including helichrysum, statice, poppy seed heads, amaranthus, spray roses and lavender.",
    img: "https://plus.unsplash.com/premium_photo-1676383427728-5e6df7edcf02?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=826&q=80",
    type: "Dried flowers",
}

];